spring.application.name=Parcial2-NCapas-00132623
spring.datasource.url=jdbc:postgresql://localhost:5432/magic_wand
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
